trigger:
  - Deployment-Webapp

variables:
  azureServiceConnectionId: 7421d281-52e1-4c64-b11d-12ee02151732
  projectRoot: $(System.DefaultWorkingDirectory
  pythonVersion: "3.9"


stages:
  - stage: Build
    displayName: Build and Push
    pool:
      name: Default
    jobs:
      - job: install_dependencies
        steps:
          - script: az login --identity
            displayName: Authenticate Azure CLI using private agent identity
          - script: apt update
            displayName: apt update database
          - script: apt install python python-pip
            displayName: apt install python and pip
          - script: python -m pip install --upgrade flask
            displayName: Install flask application
          - script: |
              python -m venv antenv
              source antenv/bin/activate
              python -m pip install --upgrade pip
              pip install setup
              pip install -r requirements.txt
              az deployment group create --template-file $(templateFile)
            workingDirectory: $(projectRoot)
            displayName: "Install requirements"

          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(projectRoot)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: "Upload package"
            artifact: drop

  - stage: Deploy
    displayName: "Deploy Web App"
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: DeploymentJob
      strategy:
        runOnce:
          deploy:
            steps:
              - task: UsePythonVersion@0
                inputs:
                  versionSpec: "$(pythonVersion)"
                displayName: "Use Python version"

              - task: AzureWebApp@1
                displayName: "Deploy Azure Web App : Mixit Personal Assitant"
                inputs:
                  azureSubscription: $(azureServiceConnectionId)
                  appName: $(webAppName)
                  package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip  